### ISSUE TITLE
Cannot read property 'device' when importing package

### ISSUE THREAD

**Issue by interianow** [rhdeck/react-aws-iot-provider#2]
### Description
Running `import { AWSIOTProvider } from "react-aws-iot-provider";` results in error being thrown

![img-0449](https://user-images.githubusercontent.com/29824849/45458857-ab15a300-b6c3-11e8-9ea5-44b465357ac6.JPG)

I saw that AWSIoTData is imported in 2 different modules from 2 different packages.

> entry.js

`const AWSIoTData = require("aws-iot-device-sdk");`

> index.js

`import { AWSIoTData } from "./aws-iot-device-sdk-js-react-native";`

`aws-iot-device-sdk-js-react-native` is also not defined as a dependency for react-aws-iot-provider/package.json.

Tried adding it and it did not fix the problem. I only looked at it for a few minutes,

**Comment by rhdeck** [comment]
Will check it out in am before I go. But you can import device from the
module directly instead IIRC

**Comment by rhdeck** [comment]
fixed via PR
